name: fludashboard
channels:
- conda-forge
- defaults
dependencies:
- bokeh=0.12.2=py35_0
- cligj=0.4.0=py35_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::blas=1.1=openblas
- conda-forge::brewer2mpl=1.4.1=py35_1
- conda-forge::ca-certificates=2016.8.31=0
- conda-forge::cairo=1.12.18=8
- conda-forge::certifi=2016.8.31=py35_0
- conda-forge::click=6.6=py35_0
- conda-forge::click-plugins=1.0.3=py35_0
- conda-forge::curl=7.49.1=1
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::descartes=1.0.2=py35_0
- conda-forge::entrypoints=0.2.2=py35_0
- conda-forge::expat=2.1.0=2
- conda-forge::fiona=1.7.0=np111py35_2
- conda-forge::flask=0.11.1=py35_0
- conda-forge::folium=0.2.1=py35_0
- conda-forge::fontconfig=2.11.1=3
- conda-forge::freetype=2.6.3=1
- conda-forge::freexl=1.0.2=1
- conda-forge::gdal=2.1.1=np111py35_2
- conda-forge::geopandas=0.2.1=py35_0
- conda-forge::geopy=1.10.0=py35_0
- conda-forge::geos=3.4.2=2
- conda-forge::gettext=0.19.7=1
- conda-forge::ggplot=0.11.2=py35_0
- conda-forge::giflib=5.1.4=0
- conda-forge::glib=2.48.0=4
- conda-forge::harfbuzz=1.0.6=0
- conda-forge::hdf4=4.2.12=0
- conda-forge::hdf5=1.8.17=5
- conda-forge::holoviews=1.6.2=py35_0
- conda-forge::icu=56.1=4
- conda-forge::ipykernel=4.5.0=py35_0
- conda-forge::ipython=5.1.0=py35_0
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ipywidgets=5.2.2=py35_0
- conda-forge::itsdangerous=0.24=py35_0
- conda-forge::jinja2=2.8=py35_1
- conda-forge::jpeg=9b=0
- conda-forge::json-c=0.12=0
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter_client=4.4.0=py35_0
- conda-forge::jupyter_console=5.0.0=py35_0
- conda-forge::jupyter_contrib_core=0.3.0=py35_0
- conda-forge::jupyter_core=4.2.0=py35_0
- conda-forge::jupyter_nbextensions_configurator=0.2.2=py35_0
- conda-forge::kealib=1.4.6=3
- conda-forge::libdap4=3.18.0=2
- conda-forge::libffi=3.2.1=2
- conda-forge::libiconv=1.14=3
- conda-forge::libnetcdf=4.4.1=0
- conda-forge::libpng=1.6.24=0
- conda-forge::libpq=9.5.4=2
- conda-forge::libsodium=1.0.10=0
- conda-forge::libspatialindex=1.8.5=1
- conda-forge::libspatialite=4.3.0a=9
- conda-forge::libtiff=4.0.6=6
- conda-forge::libuuid=1.0.3=1
- conda-forge::libxml2=2.9.4=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::matplotlib=1.5.3=np111py35_0
- conda-forge::mistune=0.7.3=py35_0
- conda-forge::munch=2.0.4=py35_0
- conda-forge::nbconvert=4.2.0=py35_0
- conda-forge::nbformat=4.1.0=py35_0
- conda-forge::ncurses=5.9=9
- conda-forge::notebook=4.2.3=py35_0
- conda-forge::numpy=1.11.1=py35_blas_openblas_201
- conda-forge::openblas=0.2.18=5
- conda-forge::openjpeg=2.1.0=6
- conda-forge::openssl=1.0.2h=2
- conda-forge::pandas=0.18.1=np111py35_1
- conda-forge::pango=1.40.1=0
- conda-forge::patsy=0.4.1=py35_0
- conda-forge::pcre=8.38=1
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=8.1.2=py35_0
- conda-forge::pixman=0.32.6=0
- conda-forge::proj.4=4.9.2=0
- conda-forge::prompt_toolkit=1.0.7=py35_0
- conda-forge::psycopg2=2.6.2=py35_1
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::pyparsing=2.1.8=py35_0
- conda-forge::pyproj=1.9.5.1=py35_0
- conda-forge::pyqt=4.11.4=py35_0
- conda-forge::pysal=1.11.2=py35_0
- conda-forge::python=3.5.2=3
- conda-forge::python-dateutil=2.5.3=py35_0
- conda-forge::pytz=2016.6.1=py35_0
- conda-forge::pyyaml=3.11=py35_0
- conda-forge::pyzmq=15.4.0=py35_0
- conda-forge::qt=4.8.7=1
- conda-forge::qtconsole=4.2.1=py35_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.11.1=py35_0
- conda-forge::rtree=0.8.2=py35_0
- conda-forge::scipy=0.18.0=np111py35_blas_openblas_202
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::setuptools=26.1.1=py35_0
- conda-forge::shapely=1.5.17=np111py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::statsmodels=0.6.1=np111py35_0
- conda-forge::terminado=0.6=py35_0
- conda-forge::tk=8.5.19=0
- conda-forge::tornado=4.4.1=py35_1
- conda-forge::traitlets=4.3.0=py35_0
- conda-forge::vincent=0.4.4=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::werkzeug=0.11.10=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::widgetsnbextension=1.2.6=py35_3
- conda-forge::xerces-c=3.1.4=2
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zlib=1.2.8=3
- jupyter=1.0.0=py35_3
- lancet=0.9.0=py35_0
- libgfortran=3.0.0=1
- param=1.3.2=py35_0
- sqlalchemy=1.0.13=py35_0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - brewer2mpl==1.4.1
  - certifi==2016.8.31
  - click==6.6
  - click-plugins==1.0.3
  - cycler==0.10.0
  - decorator==4.0.10
  - descartes==1.0.2
  - fiona==1.7.0.post2
  - flask==0.11.1
  - folium==0.2.1
  - gdal==2.1.1
  - geopandas==0.2.1
  - geopy==1.10.0
  - ggplot==0.11.2
  - holoviews==1.6.2
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - itsdangerous==0.24
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-core==4.2.0
  - jupyter-nbextensions-configurator==0.2.2
  - lancet-ioam==0.9.0
  - markupsafe==0.23
  - matplotlib==1.5.3
  - mistune==0.7.3
  - munch==2.0.4
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - notebook==4.2.3
  - numpy==1.11.1
  - pandas==0.18.1
  - patsy==0.4.1
  - pexpect==4.2.1
  - pickleshare==0.7.3
  - pip==8.1.2
  - prompt-toolkit==1.0.7
  - psycopg2==2.6.2
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.8
  - pyproj==1.9.5.1
  - pysal==1.11.2
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyyaml==3.11
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - requests==2.11.1
  - rtree==0.8.2
  - scipy==0.18.0
  - seaborn==0.7.1
  - setuptools==26.1.1.post20160901
  - shapely==1.5.17
  - simplegeneric==0.8.1
  - six==1.10.0
  - statsmodels==0.6.1
  - terminado==0.6
  - tornado==4.4.1
  - traitlets==4.3.0
  - vincent==0.4.4
  - wcwidth==0.1.7
  - werkzeug==0.11.10
  - wheel==0.29.0
  - widgetsnbextension==1.2.6
